### ISSUE TITLE
Institutional memory

### ISSUE THREAD

**Issue by aubertc** [DisCoTec/discotec.github.io#11]
On 

https://www.discotec.org/#discotec-editions

you could add for the 2013 edition a link to 

https://web.archive.org/web/20130525064342/http://www.discotec.org/

**Comment by basvdheuvel** [comment]
Good suggestion. I followed suit and fixed the links to all past editions: https://github.com/DisCoTec/discotec.github.io/commit/2e0ac9ceb9e5e85bfd0b1598b067422c6b041962
